# Site settings
title: Magic Mirror for Sketch 3
email: james@magicmirror.design
description: When Sketch Meets Perspective Mockups. A Powerful Sketch 3 Plugin to Perspective Transform Artboards into Shapes, just like Smart Objects in Photoshop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicmirror.design" # the base hostname & protocol for your site
downloadurl: "http://api.magicmirror.design/download"
author: James Tang
twitter_username: jamztang
github_username:  jamztang
analytics:
  google: UA-65727569-1
  mixpanel: 3cfd84dad73057910e2e1ca896a4ab6b


# Build settings
markdown: kramdown

collections:
  templates:
    output: true
    permalink: /templates/:path/

defaults:
  - scope:
      type: templates
    values:
      layout: template
