# Site settings
title: Magic Mirror for Sketch 3
email: james@magicmirror.design
description: Powerful Sketch 3 plugin that adds perspective transformation functionality to Sketch, just like Smart Objects in Photoshop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicmirror.design" # the base hostname & protocol for your site
twitter_username: jamztang
github_username:  jamztang

# Build settings
markdown: kramdown
